name: Test plone.app.tiles

on:
  # push:
  #   branches:
  #     - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        plone:
          - ["3.8", "5.2-latest"]
          - ["3.11", "6.0-latest"]
          - ["3.12", "6.1-dev"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Plone ${{ matrix.plone[1] }} with Python ${{ matrix.plone[0] }}
        id: setup
        uses: plone/setup-plone@v2.0.0
        with:
          python-version: ${{ matrix.plone[0] }}
          plone-version: ${{ matrix.plone[1] }}

      - name: Install package
        run: |
          mv requirements-${{ matrix.plone[1] }}.txt requirements.txt
          make VENV=off install

      - name: Run tests
        run: |
          make VENV=off test-ignore-warnings
